### ISSUE TITLE
Intermittent CI errors

### ISSUE THREAD

**Issue by kpaulisse** [github/octocatalog-diff#104]
CI jobs occasionally fail with:

```
  1) preserve environments integration with --preserve-environments set and --environment, --create-symlinks unset should exit with error status due modules in production environment not being found
     Failure/Error: expect(@result.exception).to be_a_kind_of(OctocatalogDiff::Errors::CatalogError)
       expected #<Parallel::DeadWorker: Parallel::DeadWorker> to be a kind of OctocatalogDiff::Errors::CatalogError
     # ./spec/octocatalog-diff/integration/preserve_environments_spec.rb:97:in `block (4 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:112:in `block in run'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:101:in `loop'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:101:in `run'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-retry-0.5.0/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.0.0/gems/rspec-retry-0.5.0/lib/rspec/retry.rb:30:in `block (2 levels) in setup'
```

It looks like we need to rescue `Parallel::DeadWorker` and raise `OctocatalogDiff::Errors::CatalogError` at some point.

**Comment by kpaulisse** [comment]
Resolved by https://github.com/github/octocatalog-diff/issues/111
