### ISSUE TITLE
httparty v0.15.2 breaks octocatalog-diff

### ISSUE THREAD

**Issue by westbywest** [github/octocatalog-diff#117]
> Description of problem

The version of httparty gem released a few days ago, 0.15.2, doesn't work with current octocatalog-diff gem, error quoted below.  The problem went away upon reverting to httparty v0.14.0.

> Command used and debugging output

With httparty gem v0.15.2 installed, querying octocatalog-diff version fails:
```
$ ~/bin/octocatalog-diff --version
/home/puppetdiff/.gem/ruby/gems/httparty-0.15.2/lib/httparty/response/headers.rb:3:in `<class:Response>': uninitialized constant SimpleDelegator (NameError)
	from /home/puppetdiff/.gem/ruby/gems/httparty-0.15.2/lib/httparty/response/headers.rb:2:in `<module:HTTParty>'
	from /home/puppetdiff/.gem/ruby/gems/httparty-0.15.2/lib/httparty/response/headers.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/puppetdiff/.gem/ruby/gems/httparty-0.15.2/lib/httparty/response.rb:105:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/puppetdiff/.gem/ruby/gems/httparty-0.15.2/lib/httparty.rb:641:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/httparty.rb:3:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/puppetdb.rb:4:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/puppetdb.rb:4:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/facts/puppetdb.rb:5:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/facts/puppetdb.rb:5:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/facts.rb:6:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/facts.rb:6:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog-util/builddir.rb:5:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog-util/builddir.rb:5:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog/computed.rb:8:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog/computed.rb:8:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog.rb:6:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog.rb:6:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/api/v1/catalog.rb:4:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/api/v1/catalog.rb:4:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/api/v1.rb:3:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/api/v1.rb:3:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff.rb:5:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff.rb:5:in `block in <top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff.rb:5:in `each'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff.rb:5:in `<top (required)>'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/bin/octocatalog-diff:16:in `require_relative'
	from /home/puppetdiff/.gem/ruby/gems/octocatalog-diff-1.1.0/bin/octocatalog-diff:16:in `<top (required)>'
	from /home/puppetdiff/bin/octocatalog-diff:23:in `load'
	from /home/puppetdiff/bin/octocatalog-diff:23:in `<main>'
```

> Platform and version information

- Your OS: CentOS v7.3.1611
- Your Ruby version: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
- Your version of Puppet: open source Puppet v4.6.2
- Your version of octocatalog-diff: 1.1.0

> Do the tests pass from a clean checkout?

Same error received as with octocatalog-diff --version .

**Comment by kpaulisse** [comment]
There's a new httparty release - https://rubygems.org/gems/httparty/versions/0.15.4

Could you see if you're still having the problem with that version?

**Comment by westbywest** [comment]
It's now up to httparty (0.15.5), which does appear to work.
