### ISSUE TITLE
OpenSSL::OpenSSLError password must be at least 4 bytes with ruby 2.4.0

### ISSUE THREAD

**Issue by kosfar** [github/octocatalog-diff#118]
Hi there,
trying to fire an octocatalog-diff against two branches with a command similar to the following:
`octocatalog-diff -n <hostname> --no-validate-references --no-parallel --fact-file /tmp/facts.yaml --from production --to testlints --puppet-master <my_puppet_master> --puppet-master-api-version 2 --puppet-master-ssl-ca ca.pem --puppet-master-ssl-client-cert cert.pem --puppet-master-ssl-client-key my.key --debug`

results in the following traces under ruby 2.4.0:
```
D, [2017-05-22T22:18:23.894611 #25132] DEBUG -- : Failed build_catalog for production: OpenSSL::OpenSSLError password must be at least 4 bytes
W, [2017-05-22T22:18:23.894667 #25132]  WARN -- : Failed build_catalog for production
/home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/catalogs.rb:209:in `add_parallel_result': Catalog for 'from' (production) failed to compile with OpenSSL::OpenSSLError: password must be at least 4 bytes (OctocatalogDiff::Errors::CatalogError)
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/httparty.rb:126:in `initialize'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/httparty.rb:126:in `new'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/httparty.rb:126:in `ssl_options'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/httparty.rb:83:in `wrap_ssl_options'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/httparty.rb:28:in `post'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog/puppetmaster.rb:115:in `block in fetch_catalog'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog/puppetmaster.rb:111:in `upto'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog/puppetmaster.rb:111:in `fetch_catalog'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog/puppetmaster.rb:67:in `build'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/catalog.rb:59:in `build'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/catalogs.rb:221:in `build_catalog'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/parallel.rb:29:in `call'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/parallel.rb:29:in `execute'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/parallel.rb:150:in `block in run_tasks_serial'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/parallel.rb:147:in `each'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/parallel.rb:147:in `run_tasks_serial'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/parallel.rb:75:in `run_tasks'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/catalogs.rb:92:in `build_catalog_parallelizer'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/catalogs.rb:29:in `catalogs'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/api/v1/catalog-diff.rb:34:in `catalog_diff'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/api/v1.rb:19:in `catalog_diff'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/cli.rb:112:in `cli'
   /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/bin/octocatalog-diff:34:in `<top (required)>'
   /home/kosfar/.rvm/gems/ruby-2.4.0/bin/octocatalog-diff:22:in `load'
   /home/kosfar/.rvm/gems/ruby-2.4.0/bin/octocatalog-diff:22:in `<main>'
   /home/kosfar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
   /home/kosfar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/catalogs.rb:112:in `block in build_catalog_parallelizer'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/catalogs.rb:106:in `each'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/catalogs.rb:106:in `build_catalog_parallelizer'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/util/catalogs.rb:29:in `catalogs'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/api/v1/catalog-diff.rb:34:in `catalog_diff'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/api/v1.rb:19:in `catalog_diff'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/lib/octocatalog-diff/cli.rb:112:in `cli'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.1.0/bin/octocatalog-diff:34:in `<top (required)>'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/bin/octocatalog-diff:22:in `load'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/bin/octocatalog-diff:22:in `<main>'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/kosfar/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'


```
My gem list:
```
** LOCAL GEMS ***

bigdecimal (default: 1.3.0)
bundler (1.14.6)
bundler-unload (1.0.2)
did_you_mean (1.1.0)
diffy (3.2.0)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
hashdiff (0.3.4)
httparty (0.15.5, 0.15.2)
io-console (default: 0.4.6)
json (default: 2.0.2)
minitest (5.10.1)
multi_xml (0.6.0)
net-telnet (0.1.1)
octocatalog-diff (1.1.0)
openssl (default: 2.0.2)
parallel (1.11.2)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
rubygems-bundler (1.4.4)
rugged (0.26.0b5)
rvm (1.11.3.9)
test-unit (3.2.3)
xmlrpc (0.2.1)
```

I tried also with two versions of httparty 0.15.2 and 0.15.4 but the same error persists. Running the same octocatalog-diff with ruby 2.1 is completely successful.

Platform and version information:
- my OS: Ubuntu 14.04.5 LTS
- my Ruby version: ruby 2.4.0p0 (2016-12-24 revision 57164)
- my version of Puppet: 3.8.7-1puppetlabs1

**Comment by kpaulisse** [comment]
@kosfar could you try this with the latest (1.2.0)? I believe this problem to be fixed as of this version, specifically https://github.com/github/octocatalog-diff/pull/110.

**Comment by kosfar** [comment]
@kpaulisse ruby 2.4.0p0 (2016-12-24 revision 57164) and octocatalog-diff 1.2.0 are working smoothly. I consider this issue closed

**Comment by jakeonrails** [comment]
Any idea if this was a code change to octocatalog, or an updated dependency (httparty?). I'm getting this same error in my Rails project that does not use octocatalog and wondering if you have any hints at what actually caused the issue?

**Comment by jakeonrails** [comment]
@kosfar would you possibly be able to share a diff of your Gemfile.lock pre/post upgrading octocatalog?

**Comment by kpaulisse** [comment]
> Any idea if this was a code change to octocatalog, or an updated dependency (httparty?)

I'm pretty sure it was the ruby update to 2.4. This is where I encountered (and fixed) it:

https://github.com/github/octocatalog-diff/pull/110/files#diff-4014573f90ffed0dae6cb7006673e510R122

**Comment by jakeonrails** [comment]
Ah, thank you for pointing me in that direction!
