### ISSUE TITLE
Ignore changes on attributes fails using OctocatalogDiff::API::V1.catalog_diff

### ISSUE THREAD

**Issue by baurmatt** [github/octocatalog-diff#175]
> Description of problem

- What did you do?

I've basically used the last example of https://github.com/github/octocatalog-diff/blob/master/doc/dev/api/v1/calls/catalog-diff.md#controlling-diffs and extended it a little bit.

```ruby
...
catalog_diff_result = OctocatalogDiff::API::V1.catalog_diff(
  {
    :to_catalog   => catalog_new.path,
    :from_catalog => catalog_old.path,
    :ignore       => [
      {
        type: Regexp.new('\AFile\z'),
        attr: Regexp.new("\Aparameters\f(owner|group|ensure|alias)\z"),
      },
    ],
  }
)
...
```

- What happened?
```bash
mbaur@example:~ $ ./diffenvs -e pp_4635 -n server666 --no-puppet
I, [2018-02-12T13:39:06.453395 #29060]  INFO -- : Running diffenvs for server123 (production <=> pp_4635)
/home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:398:in `=~': no implicit conversion of Regexp into String (TypeError)
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:398:in `ignore_match?'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:442:in `block in ignored?'
	from /home/mbaur/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/set.rb:324:in `each_key'
	from /home/mbaur/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/set.rb:324:in `each'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:441:in `ignored?'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:222:in `block in filter_diffs_for_ignored_items'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:222:in `reject!'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:222:in `filter_diffs_for_ignored_items'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:191:in `catdiff'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/catalog-diff/differ.rb:80:in `diff'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/cli/diffs.rb:34:in `diffs'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/api/v1/catalog-diff.rb:54:in `catalog_diff'
	from /home/mbaur/.rvm/gems/ruby-2.4.0/gems/octocatalog-diff-1.5.2/lib/octocatalog-diff/api/v1.rb:19:in `catalog_diff'
	from diffenvs:140:in `<main>'
```
- What did you expect to happen?
Changes on owner/group/ensure/alias parameters for file resources get ignored.

- How can someone reproduce the problem?
The code above should reliably fail.  

> Command used and debugging output
See above

> Platform and version information

- Your OS: Ubuntu 14.04.5rzuvb
- Your Ruby version: 2.4.0
- Your version of Puppet: 5.3.4
- Your version of octocatalog-diff: 1.5.2

> Do the tests pass from a clean checkout?
Using octocatalog-diff from gem.

> Anything else to add that you think will be helpful?

**Comment by baurmatt** [comment]
Workaround:

```ruby
catalog_diff_result = OctocatalogDiff::API::V1.catalog_diff(
  {
    :to_catalog   => catalog_new.path,
    :from_catalog => catalog_old.path,
    :ignore       => [
      {
        type: Regexp.new('\AFile\z'),
        attr: "parameters\fensure"
      },
      {
        type: Regexp.new('\AFile\z'),
        attr: "parameters\falias"
      },
      {
        type: Regexp.new('\AFile\z'),
        attr: "parameters\fowner"
      },
      {
        type: Regexp.new('\AFile\z'),
        attr: "parameters\fgroup"
      },
    ],
  }
)
```
