### ISSUE TITLE
Could not find rake-12.3.1 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by BarnumD** [github/octocatalog-diff#193]
I'm attempting to get oc-d working in a docker container so that I can integrate it into gitlab CI.  But before i've even gotten to that point, I'm trying to run based on the octocatalog-diff gem with `bin/octocatalog-diff -n myhost.domain.com --bootstrap-current --debug`.  However, I'm getting the following error
```
D, [2018-07-26T18:23:40.864494 #3596] DEBUG -- : Installed fact file at /tmp/ocd-ipc-20180726-3594-s12yxs/ocd-builddir-20180726-3596-15qo8tk/var/yaml/facts/myhost.domain.com.yaml
D, [2018-07-26T18:23:41.228157 #3596] DEBUG -- : Failed build_catalog for origin/octocatalog: OctocatalogDiff::Util::ScriptRunner::ScriptException STDOUT:
STDERR:
  /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find rake-12.3.1 in any of the sources (Bundler::GemNotFound)
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:85:in `map!'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:85:in `materialize'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/definition.rb:171:in `specs'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/definition.rb:238:in `specs_for'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/definition.rb:227:in `requested_specs'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:108:in `block in definition_method'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:20:in `setup'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler.rb:107:in `setup'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/setup.rb:20:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /code/bin/puppet:27:in `<main>'
D, [2018-07-26T18:23:41.240862 #3594] DEBUG -- : PID=3596 completed in 4.1148128 seconds, 50138 bytes
/usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/scriptrunner.rb:65:in `run': STDOUT: (OctocatalogDiff::Util::ScriptRunner::ScriptException)
STDERR:
  /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find rake-12.3.1 in any of the sources (Bundler::GemNotFound)
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:85:in `map!'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/spec_set.rb:85:in `materialize'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/definition.rb:171:in `specs'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/definition.rb:238:in `specs_for'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/definition.rb:227:in `requested_specs'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:108:in `block in definition_method'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:20:in `setup'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler.rb:107:in `setup'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.3/lib/bundler/setup.rb:20:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /code/bin/puppet:27:in `<main>'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/puppetversion.rb:34:in `puppet_version'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/catalog/computed.rb:51:in `puppet_version'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/catalog/computed.rb:213:in `block in run_puppet'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/catalog/computed.rb:210:in `upto'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/catalog/computed.rb:210:in `run_puppet'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/catalog/computed.rb:114:in `build_catalog'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/catalog.rb:96:in `build'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/catalogs.rb:241:in `build_catalog'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:34:in `call'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:34:in `execute'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:193:in `execute_task'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:119:in `block (2 levels) in run_tasks_parallel'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:117:in `fork'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:117:in `block in run_tasks_parallel'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:114:in `each'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:114:in `each_with_index'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:114:in `run_tasks_parallel'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/parallel.rb:94:in `run_tasks'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/catalogs.rb:92:in `build_catalog_parallelizer'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/util/catalogs.rb:29:in `catalogs'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/api/v1/catalog-diff.rb:34:in `catalog_diff'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/api/v1.rb:19:in `catalog_diff'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/lib/octocatalog-diff/cli.rb:119:in `cli'
        from /usr/local/rvm/gems/ruby-2.4.4/gems/octocatalog-diff-1.5.3/bin/octocatalog-diff:34:in `<top (required)>'
        from bin/octocatalog-diff:29:in `load'
        from bin/octocatalog-diff:29:in `<main>'
```

This seems to be similar to Issue #8.  When I ran `bundle update` to install the octocatalog-diff gem, among others, it installed rake version 12.3.1 into the ./bin/ folder. (under my current directory - the git repo).  However, Apparently when ruby is installed it's also installing another gem at location `/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.0.0`.  Although it's interesting - when I run `/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake --version` or just `rake --version` both provide `rake, version 12.3.1`.

So i'm confused at what to do, exactly, to get past this error.

`octocatalog-diff --version`: octocatalog-diff 1.5.3

**Comment by BarnumD** [comment]
I also tried this, but I get the same error.
```
gem install rake
Successfully installed rake-12.3.1
Parsing documentation for rake-12.3.1
Installing ri documentation for rake-12.3.1
Done installing documentation for rake after 0 seconds
1 gem installed
```

**Comment by BarnumD** [comment]
I believe I may have had some stagnant data in my attached repo bind-mount volume.  I removed recreated the container, removed 'bin', 'vendor', 'Gemfile.lock', or '.bundle' from my working directory and ran bundle update again and got past this error.  However, now i'm trying to get past `can't find gem puppet (>= 0.a) (Gem::GemNotFoundException)`

**Comment by BarnumD** [comment]
Was able to get past that by hard-coding `settings[:puppet_binary] = '/usr/local/rvm/gems/ruby-2.4.4/gems/puppet-5.5.3/bin/puppet'` instead of `settings[:puppet_binary] = '/usr/local/rvm/gems/ruby-2.4.4/bin/puppet'`.  Now i've got 
```
scriptrunner.rb:65:in `run': STDOUT: (OctocatalogDiff::Util::ScriptRunner::ScriptException)
STDERR:
  cannot load such file -- puppet/util/command_line
```
Seems like it doesn't have the PATH or environment.

**Comment by BarnumD** [comment]
I realized in this situation I had to tell my bootstrap.sh file to run bundle update again, because when the git directory was copied in it no longer had the copy that I was working off of.  That cleared up the last of the errors.
