### ISSUE TITLE
Problems with a enc consists of muliple scripts

### ISSUE THREAD

**Issue by baurmatt** [github/octocatalog-diff#27]
> Description of problem

- What did you do?
Ran octocatalog-diff with our custom (fucked up) enc
- What happened?
``` 
D, [2016-11-24T15:00:05.931292 #1593] DEBUG -- : Failed build_catalog for .: RuntimeError Failed ENC: ENC failed with status 1:  Traceback (most recent call last):
  File "/tmp/enc.sh20161124-1593-16vk0w3", line 15, in <module>
    from lib import enc_lib
ImportError: No module named lib
```
- What did you expect to happen?
Just execute the enc script without copy it to a different path
- How can someone reproduce the problem?
Build a enc which depends on multiple files

> Command used and debugging output

```
mbaur@pm3:~/syseleven-base$ ../octocatalog-diff/bin/octocatalog-diff --puppetdb-api-version 3 -n foo.lb --debug
D, [2016-11-24T15:00:05.796297 #1585] DEBUG -- : Running octocatalog-diff 0.5.6 with ruby 2.3.3
D, [2016-11-24T15:00:05.796370 #1585] DEBUG -- : Command line arguments: ["--puppetdb-api-version", "3", "-n", "foo.lb", "--debug"]
D, [2016-11-24T15:00:05.796412 #1585] DEBUG -- : Running on host hostname.net (x86_64-linux)
D, [2016-11-24T15:00:05.796955 #1585] DEBUG -- : Cached master dir: bootstrapped=bad2f1099ebb919fb2ff4f829852a9a0a1adf736; current=bad2f1099ebb919fb2ff4f829852a9a0a1adf736

▽
D, [2016-11-24T15:00:05.796984 #1585] DEBUG -- : Setting --bootstrapped-from-dir=/home/mbaur/.octocatalog-diff-cache
D, [2016-11-24T15:00:05.797154 #1585] DEBUG -- : Initialized OctocatalogDiff::Catalog::Computed for from-catalog
D, [2016-11-24T15:00:05.797184 #1585] DEBUG -- : Initialized OctocatalogDiff::Catalog::Computed for to-catalog
D, [2016-11-24T15:00:05.797221 #1585] DEBUG -- : Initialized parallel task result array: size=2
D, [2016-11-24T15:00:05.799187 #1590] DEBUG -- : Begin build_catalog for origin/master
D, [2016-11-24T15:00:05.799223 #1593] DEBUG -- : Begin build_catalog for .
D, [2016-11-24T15:00:05.799316 #1590] DEBUG -- : Setting up Puppet catalog build for origin/master
D, [2016-11-24T15:00:05.799348 #1590] DEBUG -- : Catalog for origin/master will be built with OctocatalogDiff::Catalog::Computed
D, [2016-11-24T15:00:05.799349 #1593] DEBUG -- : Setting up Puppet catalog build for .
D, [2016-11-24T15:00:05.799381 #1593] DEBUG -- : Catalog for . will be built with OctocatalogDiff::Catalog::Computed
D, [2016-11-24T15:00:05.799388 #1590] DEBUG -- : Calling build for object OctocatalogDiff::Catalog::Computed
D, [2016-11-24T15:00:05.799426 #1593] DEBUG -- : Calling build for object OctocatalogDiff::Catalog::Computed
D, [2016-11-24T15:00:05.799467 #1590] DEBUG -- : Start retrieving facts for foo.lb from OctocatalogDiff::Catalog::Computed
D, [2016-11-24T15:00:05.799500 #1590] DEBUG -- : Retrieving facts from PuppetDB
D, [2016-11-24T15:00:05.799518 #1593] DEBUG -- : Start retrieving facts for foo.lb from OctocatalogDiff::Catalog::Computed
D, [2016-11-24T15:00:05.799550 #1593] DEBUG -- : Retrieving facts from PuppetDB
D, [2016-11-24T15:00:05.882309 #1590] DEBUG -- : Success retrieving facts for foo.lb from OctocatalogDiff::Catalog::Computed
D, [2016-11-24T15:00:05.882840 #1593] DEBUG -- : Success retrieving facts for foo.lb from OctocatalogDiff::Catalog::Computed
D, [2016-11-24T15:00:05.883088 #1590] DEBUG -- : Symlinked /tmp/d20161124-1590-11wjj7b/environments/production -> /home/mbaur/.octocatalog-diff-cache
D, [2016-11-24T15:00:05.883190 #1590] DEBUG -- : Installed puppetdb.conf file at /tmp/d20161124-1590-11wjj7b/puppetdb.conf
D, [2016-11-24T15:00:05.883509 #1593] DEBUG -- : Symlinked /tmp/d20161124-1593-fi1pl2/environments/production -> /home/mbaur/syseleven-base
D, [2016-11-24T15:00:05.883612 #1593] DEBUG -- : Installed puppetdb.conf file at /tmp/d20161124-1593-fi1pl2/puppetdb.conf
D, [2016-11-24T15:00:05.884202 #1590] DEBUG -- : Installed routes.yaml file at /tmp/d20161124-1590-11wjj7b/routes.yaml
D, [2016-11-24T15:00:05.884521 #1593] DEBUG -- : Installed routes.yaml file at /tmp/d20161124-1593-fi1pl2/routes.yaml
D, [2016-11-24T15:00:05.889831 #1590] DEBUG -- : Installed fact file at /tmp/d20161124-1590-11wjj7b/var/yaml/facts/foo.lb.yaml
D, [2016-11-24T15:00:05.890053 #1593] DEBUG -- : Installed fact file at /tmp/d20161124-1593-fi1pl2/var/yaml/facts/foo.lb.yaml
D, [2016-11-24T15:00:05.931292 #1593] DEBUG -- : Failed build_catalog for .: RuntimeError Failed ENC: ENC failed with status 1:  Traceback (most recent call last):
  File "/tmp/enc.sh20161124-1593-16vk0w3", line 15, in <module>
    from lib import enc_lib
ImportError: No module named lib
``` 

> Platform and version information

- Your OS: Ubuntu 14.04
- Your Ruby version: 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
- Your version of Puppet: 3.8.7
- Your version of octocatalog-diff: octocatalog-diff 0.5.6 (Branch kpaulisse-puppetdb-v3)

**Comment by baurmatt** [comment]
I've found a workaround for this: We just set the PYTHONPATH env variable to the real path. This works for our Python script.

**Comment by kpaulisse** [comment]
Thanks for the note - I'm glad to hear you got this working.

FYI, you can also tell the program to pass certain environment variables (by default, it cleans the environment mostly to avoid strange ruby errors when octocatalog-diff runs Puppet with a different ruby than is used for Puppet). I've updated the documentation to make this more clear.
