### ISSUE TITLE
Bootstrap script can not be a absolute path

### ISSUE THREAD

**Issue by baurmatt** [github/octocatalog-diff#28]
> Description of problem

- What did you do?
Ran octocatalog-diff with `--bootstrap-script /home/mbaur/bootstrap.sh`
- What happened?
```
E, [2016-11-24T17:23:33.163444 #26833] ERROR -- : Bootstrap exception: Failed bootstrap_directory for from_dir: OctocatalogDiff::CatalogUtil::Bootstrap::BootstrapError Bootstrap script /home/mbaur/syseleven-base/home/mbaur/bootstrap.sh does not exist
```
- What did you expect to happen?
Use the absolute path
- How can someone reproduce the problem?
Run `octocatalog-diff --bootstrap-script` with an absolute path

> Command used and debugging output

```
mbaur@pm3:~/syseleven-base$ ../octocatalog-diff/bin/octocatalog-diff --puppetdb-api-version 3 -n foo.lb --pass-env-vars PYTHONPATH --no-parallel --bootstrap-script /home/mbaur/bootstrap.sh --debug
D, [2016-11-24T17:23:33.074947 #26833] DEBUG -- : Running octocatalog-diff 0.5.6 with ruby 2.3.3
D, [2016-11-24T17:23:33.075026 #26833] DEBUG -- : Command line arguments: ["--puppetdb-api-version", "3", "-n", "foo.lb", "--pass-env-vars", "PYTHONPATH", "--no-parallel", "--bootstrap-script", "/home/mbaur/bootstrap.sh", "--debug"]
D, [2016-11-24T17:23:33.075062 #26833] DEBUG -- : Running on host hostname.net (x86_64-linux)
D, [2016-11-24T17:23:33.075614 #26833] DEBUG -- : Begin bootstrap cached master directory
D, [2016-11-24T17:23:33.075640 #26833] DEBUG -- : Begin bootstrap_then_exit
D, [2016-11-24T17:23:33.075680 #26833] DEBUG -- : Begin 1 bootstrap(s)
D, [2016-11-24T17:23:33.075729 #26833] DEBUG -- : Begin bootstrap from_dir /home/mbaur/.octocatalog-diff-cache for origin/master
D, [2016-11-24T17:23:33.075756 #26833] DEBUG -- : Begin git checkout /home/mbaur/syseleven-base:origin/master -> /home/mbaur/.octocatalog-diff-cache
D, [2016-11-24T17:23:33.076076 #26833] DEBUG -- : Begin git archive /home/mbaur/syseleven-base:origin/master -> /home/mbaur/.octocatalog-diff-cache
D, [2016-11-24T17:23:33.163145 #26833] DEBUG -- : Success git archive /home/mbaur/syseleven-base:origin/master
D, [2016-11-24T17:23:33.163308 #26833] DEBUG -- : Success git checkout /home/mbaur/syseleven-base:origin/master -> /home/mbaur/.octocatalog-diff-cache
D, [2016-11-24T17:23:33.163380 #26833] DEBUG -- : Failed bootstrap from_dir /home/mbaur/.octocatalog-diff-cache for origin/master: OctocatalogDiff::CatalogUtil::Bootstrap::BootstrapError Bootstrap script /home/mbaur/syseleven-base/home/mbaur/bootstrap.sh does not exist
D, [2016-11-24T17:23:33.163412 #26833] DEBUG -- : Success bootstrap from_dir /home/mbaur/.octocatalog-diff-cache for origin/master
E, [2016-11-24T17:23:33.163444 #26833] ERROR -- : Bootstrap exception: Failed bootstrap_directory for from_dir: OctocatalogDiff::CatalogUtil::Bootstrap::BootstrapError Bootstrap script /home/mbaur/syseleven-base/home/mbaur/bootstrap.sh does not exist
/home/mbaur/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:44:in `rescue in bootstrap_then_exit': Bootstrap exception: Failed bootstrap_directory for from_dir: OctocatalogDiff::CatalogUtil::Bootstrap::BootstrapError Bootstrap script /home/mbaur/syseleven-base/home/mbaur/bootstrap.sh does not exist (OctocatalogDiff::CatalogDiff::Cli::Catalogs::BootstrapError)
	from /home/mbaur/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli/catalogs.rb:38:in `bootstrap_then_exit'
	from /home/mbaur/octocatalog-diff/lib/octocatalog-diff/catalog-util/cached_master_directory.rb:136:in `git_repo_checkout_bootstrap'
	from /home/mbaur/octocatalog-diff/lib/octocatalog-diff/catalog-util/cached_master_directory.rb:47:in `run'
	from /home/mbaur/octocatalog-diff/lib/octocatalog-diff/catalog-diff/cli.rb:96:in `cli'
	from ../octocatalog-diff/bin/octocatalog-diff:74:in `<main>'
```

> Platform and version information

- Your OS: Ubuntu 14.04
- Your Ruby version: 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
- Your version of Puppet: 3.8.7
- Your version of octocatalog-diff: octocatalog-diff 0.5.6 (Branch kpaulisse-puppetdb-v3)

**Comment by kpaulisse** [comment]
Hey @baurmatt thanks for the report.

Can you try out the latest branch found in https://github.com/github/octocatalog-diff/pull/34 to see if it fixes the problem for you?

**Comment by baurmatt** [comment]
Works fine, thanks a lot! :)
